// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EPhEJGU0UtEUwcEivV9XffrQPZdDgTM',
    appId: '1:475532466595:web:1ecdeeb8b12fa9e86be216',
    messagingSenderId: '475532466595',
    projectId: 'abdulhai-6c45d',
    authDomain: 'abdulhai-6c45d.firebaseapp.com',
    storageBucket: 'abdulhai-6c45d.firebasestorage.app',
    measurementId: 'G-6E2XQDLMML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgS27tTJOq3kCWNMW_encTwLvKuHgKB9s',
    appId: '1:475532466595:android:3d3187df6d88b20b6be216',
    messagingSenderId: '475532466595',
    projectId: 'abdulhai-6c45d',
    storageBucket: 'abdulhai-6c45d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzmMSXfJFv-5qWO9dusG8lMfA3Mj1YXdw',
    appId: '1:475532466595:ios:ed6d9a84d32923a46be216',
    messagingSenderId: '475532466595',
    projectId: 'abdulhai-6c45d',
    storageBucket: 'abdulhai-6c45d.firebasestorage.app',
    iosBundleId: 'com.innovativewidget.squareAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzmMSXfJFv-5qWO9dusG8lMfA3Mj1YXdw',
    appId: '1:475532466595:ios:1baf5f036dd126086be216',
    messagingSenderId: '475532466595',
    projectId: 'abdulhai-6c45d',
    storageBucket: 'abdulhai-6c45d.firebasestorage.app',
    iosBundleId: 'com.example.squareoneAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9EPhEJGU0UtEUwcEivV9XffrQPZdDgTM',
    appId: '1:475532466595:web:c156ba7c9a0816706be216',
    messagingSenderId: '475532466595',
    projectId: 'abdulhai-6c45d',
    authDomain: 'abdulhai-6c45d.firebaseapp.com',
    storageBucket: 'abdulhai-6c45d.firebasestorage.app',
    measurementId: 'G-7H09GG7M2M',
  );
}
